### ISSUE TITLE
Upgrade Production Database

### ISSUE THREAD

**Issue by s2t2** [OpenSaltLake/utah-court-calendar-service#11]
message from heroku:

> The database DATABASE_URL on Heroku app utah-court-calendar-service has exceeded its allocated storage capacity. Immediate action is required.

> The database contains 13,653 rows, exceeding the Hobby-dev plan limit of 10,000. INSERT privileges to the database will be automatically revoked in 7 days. This will cause service failures in most applications dependent on this database.

> To avoid a disruption to your service, migrate the database to a Hobby Basic ($9/month) or higher database plan:

> https://devcenter.heroku.com/articles/upgrade-heroku-postgres-with-pgbackups

> If you are unable to upgrade the database, you should reduce the number of records stored in it.

**Comment by todrobbins** [comment]
BIG DATA

![bq5ocg9cmaezedv](https://cloud.githubusercontent.com/assets/158590/13366000/b4fbfadc-dc95-11e5-8050-7b401eb9576d.jpg)

**Comment by s2t2** [comment]
http://data-creative.info/process-documentation/2015/07/25/how-to-deploy-a-rails-app-to-heroku.html#database-upgrades
