### ISSUE TITLE
Clear out redundant results.

### ISSUE THREAD

**Issue by kuanb** [OpenSaltLake/utah-court-calendar-service#16]
When new dates are scraped, check to see if they are already in the system and if they are then do not insert.

We have cases of multiple entries for the same court date and identification. Here is an example:

`&defendant_name=MARTINEZ,%20JACINTA`

**Comment by s2t2** [comment]
If able to uniquely identify each event by its case number, we can filter results to include only the most recent event version. Else we can delete events from past calendars and only retain events from today's calendars. I'm leaning towards the latter, which will limit this service to a more manageable scope.
